package ic.jms.genesis;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import ic.jms.genesis.employees.TechnicalLeader;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;

import static org.junit.Assert.assertTrue;

public class CallCenterTest {

    @InjectMocks
    CallCenter callCenter = new CallCenter();

    @Mock
    private Employee specialEmployee;


    @Before
    public void beforeTest(){
        specialEmployee = new TechnicalLeader();
    }

    @Test
    public void testCallCenter_ReceiveACall() {
        callCenter.receiveACall();
    }
}
