package ic.jms.genesis;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class CallCenterTest {

    private CallCenter callCenter = CallCenter.getInstance();

    @Test
    public void testCallCenter_ReceiveACall() throws InterruptedException {
        final CountDownLatch latch = new CountDownLatch(1);
        callCenter.receiveACall();
        latch.await(1000, TimeUnit.MILLISECONDS);
    }
}
