package ic.jms.genesis;

import ic.jms.genesis.employees.Fresher;
import ic.jms.genesis.employees.ProductManager;
import ic.jms.genesis.employees.TechnicalLeader;

import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class CallCenter {

    private static final int maxEmployee = 10;
    private List<Employee> employeeList;

    public CallCenter() {
        this.addEmployee();
    }

    public void receiveACall() {

    }

    private void addEmployee() {
        if (Math.random() > 0.5) {
            employeeList.add(new TechnicalLeader());
        }
        else {
            employeeList.add(new ProductManager());
        }

        for (int i = 0; i < maxEmployee - 1; i++) {
            employeeList.add(new Fresher());
        }
    }
}
